import type { NextPage } from 'next';
import Head from 'next/head';
import NavBar from '~/components/NavBar';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>LionTown</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
    </div>
  );
};
export default Home;
