/* eslint-disable no-shadow */
import { NextPage } from 'next';
import Head from 'next/head';
import styled, { ThemeProvider } from 'styled-components';
import { theme } from '../styles/theme';
import BackgroundMain from '~DesignSystem/BackgroundMain';
import InputGroup from '~DesignSystem/InputGroup';
import Button from '../DesignSystem/Button';
// import NavBar from '~/components/NavBar';

const Home: NextPage = () => {
  return (
    <ThemeProvider theme={theme}>
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          {/* 글자 theme 예시 */}
          <H1Skyblue>text-primary-skyblue</H1Skyblue>
          <H1Brown>text-primary-brown</H1Brown>
          <H1Yellow>text-primary-yellow</H1Yellow>
          <H1Orange>text-primary-orange</H1Orange>
          <H1Green>text-primary-green</H1Green>
          <H1Lightgreen>text-primary-lightgreen</H1Lightgreen>
          <H1DefaultText>text-text</H1DefaultText>
          <H1Placeholder>text-placeholder</H1Placeholder>

          {/* 버튼 스타일링 예시 */}
          <Button size="medium">버튼</Button>
          <Button size="large" fontColor="#fff">
            버튼
          </Button>

          {/* input 스타일링 예시 */}
          <InputGroup id="input" label="이름" labelPos="up" labelDist={10} fullWidth>
            <input placeholder="asdasd" name="input" id="input" />
          </InputGroup>
          <InputGroup id="test" label="이름" labelPos="up" labelDist={10}>
            <input placeholder="asdasd" name="input" id="test" />
          </InputGroup>
          <InputGroup id="test2" label="이름" labelPos="left" labelDist={20}>
            <input placeholder="asdasd" name="input" id="test2" />
          </InputGroup>
          <InputGroup
            id="test3"
            label="이름"
            labelPos="left"
            labelDist={20}
            error="에러메시지"
            fullWidth
          >
            <input placeholder="asdasd" name="input" id="test3" />
          </InputGroup>
          <InputGroup id="test4" label="이름" labelPos="left" labelDist={20} fullWidth>
            <input placeholder="asdasd" name="input" id="test4" />
          </InputGroup>
          <BackgroundMain>
            안녕하세요! 여기는 게시판 영역입니다! 내부 콘텐츠 스탕일링은 각자 해야합니다!
          </BackgroundMain>
        </main>
      </div>
    </ThemeProvider>
  );
};

const H1Orange = styled.h1`
  color: ${({ theme }) => theme.colors.primary.orange};
`;
const H1Skyblue = styled.h1`
  color: ${({ theme }) => theme.colors.primary.skyblue};
`;
const H1Brown = styled.h1`
  color: ${({ theme }) => theme.colors.primary.brown};
`;
const H1Yellow = styled.h1`
  color: ${({ theme }) => theme.colors.primary.yellow};
`;
const H1Green = styled.h1`
  color: ${({ theme }) => theme.colors.primary.green};
`;
const H1Lightgreen = styled.h1`
  color: ${({ theme }) => theme.colors.primary.lightgreen};
`;
const H1DefaultText = styled.h1`
  color: ${({ theme }) => theme.colors.text};
`;
const H1Placeholder = styled.h1`
  color: ${({ theme }) => theme.colors.placeholder};
`;

export default Home;
