import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="text-primary-skyblue">text-primary-skyblue</h1>
        <h1 className="text-primary-brown">text-primary-brown</h1>
        <h1 className="text-primary-yellow">text-primary-yellow</h1>
        <h1 className="text-primary-orange">text-primary-orange</h1>
        <h1 className="text-primary-brown">text-primary-brown</h1>
        <h1 className="text-primary-green">text-primary-green</h1>
        <h1 className="text-primary-lightgreen">text-primary-lightgreen</h1>
        <h1 className="text-text">text-text</h1>
        <h1 className="text-placeholder">text-placeholder</h1>
      </main>
    </div>
  );
};

export default Home;
