name: Deploy Alert

on:
  workflow_run:
    workflows: ['NEXT Deploy']
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: action-slack
        uses: 8398a7/action-slack@v3

        with:
          status: custom
          custom_payload: |
            {
              text: "Custom Field Check",
              attachments: [{
                "author_name": "8398a7@action-slack", // json
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                title: '자동 배포 결과',
                text: '${{ job.status }}' === 'success' ? '성공\nhttps://mju-liontown.today' : '${{ job.status }}' === 'failure' ? '실패' : '애매합니다',
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_DEPLOY_ALERT_URL }} # required
          if: always() # Pi
