name: Deploy Alert

on:
  workflow_run:
    workflows: ['NEXT Deploy']
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: action-slack
        uses: 8398a7/action-slack@v3

        with:
          status: ${{ job.status }}
          author_name: Github Action Test # default: 8398a7@action-slack
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_DEPLOY_ALERT_URL }} # required
          if: always() # Pi
