name: NEXT Deploy
on:
  push:
    branches:
      - main
jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout source code.
  #       uses: actions/checkout@v3
  #       with:
  #         ref: main

  #     - name: Install Dependencies
  #       run: |
  #         yarn install

  #     - name: Configure AWS Credentials
  #       uses: aws-actions/configure-aws-credentials@v1
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: ap-northeast-2

  #     - name: Deploy Next.js app
  #       run: |
  #         yarn run deploy
  notify:
    # needs: build
    runs-on: ubuntu-latest

    steps:
      - name: action-slack
        uses: 8398a7/action-slack@v3

        with:
          status: custom
          custom_payload: |
            {
              text: "Custom Field Check",
              attachments: [{
                "author_name": "8398a7@action-slack", // json
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                title: '자동 배포 결과',
                text: '${{ job.status }}' === 'success' ? '성공\nhttps://mju-liontown.today' : '${{ job.status }}' === 'failure' ? '실패' : '애매합니다',
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_DEPLOY_ALERT_URL }} # required
          if: always() # Pi
