name: slack

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: action-slack
        uses: 8398a7/action-slack@v3

        with:
          status: custom
          fields: workflow,job,commit,repo,author,pullRequest
          custom_payload: |
            {
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                fields: [
                  {
                    title: '레포지토리',
                    value: `${{ github.event.repository.name }}`,
                    short: false
                  },
                  {
                    title: 'PR 제목',
                    value: `${{ github.event.pull_request.title }}`,
                    short: false
                  },
                  {
                    title: '작성자',
                    value: `${process.env.AS_AUTHOR}`,
                    short: false
                  }
                ],
                title: '>>> 리뷰하러 가기 >>>',
                title_link: '${{ github.event.pull_request.html_url }}',
                thumb_url: 'https://mblogthumb-phinf.pstatic.net/MjAxOTA4MjVfMTI3/MDAxNTY2NzM1NDY4MTA1.t0982t3b6O-vFPkCw-zhBRxqfj5qjDqepEXJAkk2F6Eg.BLPXzCBLMFarJ9QGQ6KU2pAXBnhhURkBwihBaW_rNn8g.JPEG.ondo_h/SE-2eb6c828-cc8b-4e51-a2f1-148593277123.jpg?type=w800',
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always() # Pick up events even if the job fails or is canceled.
    permissions:
      contents: read
      actions: read
